SELECT * FROM CUSTOMER;
SELECT * FROM CUSTOMERDETAILS;
SELECT * FROM CUSTOMERBILLINGADDRESS;
SELECT * FROM CUSTOMERSHIPPINGADDRESS;
SELECT * FROM CUSTOMERCART;
SELECT * FROM PRODUCT;
SELECT * FROM SUPPLIER;
SELECT * FROM XMAP_PS;


drop table CUSTOMER;
drop table CUSTOMERDETAILS;
drop table CUSTOMERBILLINGADDRESS;
drop table CUSTOMERSHIPPINGADDRESS;
drop table CUSTOMERCART;
drop table CUSTOMERCARTITEMS 